### ISSUE TITLE
npm run dev出错

### ISSUE THREAD

**Issue by 0604hx** [o2team/xcel#1]
执行完`npm install`后，
```shell
npm WARN xcel@1.3.0 No repository field.
npm WARN xcel@1.3.0 No license field.
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@2.0.2
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-linux:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-linux@1.0.3
npm WARN xcel@1.3.0 No repository field.
```

接着执行`npm run dev`，出现以下的错误信息：
```shell
starting electron...

electron  fs.js:640
            return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                           ^
          
          Error: ENOENT: no such file or directory, open '/nerve/workspace/nodejs/xcel/node_modules/electron-prebuilt/path.txt'
              at Error (native)
              at Object.fs.openSync (fs.js:640:18)
              at Object.fs.readFileSync (fs.js:508:33)
              at Object.<anonymous> (/nerve/workspace/nodejs/xcel/node_modules/electron-prebuilt/index.js:4:42)
              at Module._compile (module.js:541:32)
              at Object.Module._extensions..js (module.js:550:10)
              at Module.load (module.js:458:32)
              at tryModuleLoad (module.js:417:12)
              at Function.Module._load (module.js:409:3)
              at Module.require (module.js:468:17)
```

是否是我的electron没有正确安装？（我已经切换到淘宝npm源了）

谢谢

**Comment by chuyik** [comment]
@0604hx 是的，我估计是 Electron 没下载完毕你就 `ctrl+c` 关掉了。
建议你执行该命令：
```bash
export ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/
cd ./node_modules/electron-prebuilt && node install.js   # 重新下载 electron
```

**Comment by 0604hx** [comment]
问题已经解决！

现在看源码学习ing。我想请问一下LZ用的是什么IDE，我现在用的是VSCode（代码提示方面不是很好用，vue文件几乎没有js提示....）

**Comment by chuyik** [comment]
@JChehe 回答一下~
我个人的话用的也是 VSCode，但 Vue.js 代码提示最好的目前是 Atom，VSCode 代码提示还在路上 [vscode/issues/12354](https://github.com/Microsoft/vscode/issues/12354#issuecomment-253792896)。

Atom 的插件支持可以看 [monterail/atom-vue-hyperclick](https://github.com/monterail/atom-vue-hyperclick)。

**Comment by JChehe** [comment]
@0604hx 呃..我用的是 Sublime Text 3

**Comment by 0604hx** [comment]
非常感谢！
